from __future__ import annotations

import csv
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

ROOT_MARKERS = ('VERSION', 'configs', 'src')

EXCLUDED_PARTS = {
    '.git', '.cache', '.mypy_cache', '.pytest_cache', '.ruff_cache', '.runtime', '.tox',
    '.venv', 'venv', '__pycache__', 'dist', 'logs', 'model_cache',
    'outputs', 'run', 'node_modules',
    # .gitignore의 "Local AI/dev-agent tool state"/".other" 항목과 맞춤 — 개인 스크래치·
    # 에이전트 상태 디렉터리라 프로젝트 구조 인벤토리에 안 잡혀야 한다.
    '.other', '.agents', '.codex', '.claude', '.cursor',
}
TOP_LEVEL_EXCLUDED_PARTS = {'build', 'env', 'models'}
EXCLUDED_SUFFIXES = {'.pyc', '.pyo'}
DYNAMIC_RUNTIME_PATTERNS = ('runtime_validation_',)

CATEGORY_RULES = [
    ('src/', 'application/control-plane source'),
    ('tests/', 'test suite'),
    ('scripts/', 'operator/developer command surface'),
    ('docs/adr/', 'architecture decision record'),
    ('docs/examples/', 'documentation example'),
    ('docs/archive/', 'historical documentation archive'),
    ('docs/', 'documentation'),
    ('reports/runtime/', 'runtime/operator generated report'),
    ('reports/refactor/', 'current handoff/review report'),
    ('reports/archive/', 'historical report archive'),
    ('configs/', 'configuration source of truth'),
    ('contracts/', 'contract registry'),
    ('specs/', 'OpenAPI/JSON schema contract'),
    ('ops/', 'compose/monitoring/runtime ops template'),
    ('harness/', 'runtime validation harness plan/matrix'),
    ('model_cards/', 'model card metadata'),
    ('examples/', 'request example'),
]

OWNER_RULES = [
    ('src/ai_model_serving/domain/', 'domain-registry'),
    ('src/ai_model_serving/contracts/', 'api-contracts'),
    ('src/ai_model_serving/runtime_validation/', 'runtime-validation'),
    ('src/ai_model_serving/governance_validation/', 'governance-validation'),
    ('src/', 'application'),
    ('tests/', 'quality'),
    ('scripts/', 'operator-ux'),
    ('docs/', 'documentation'),
    ('reports/', 'handoff-reporting'),
    ('configs/', 'configuration'),
    ('ops/', 'operations'),
    ('specs/', 'api-contracts'),
]

MANAGEMENT_RULES = [
    ('configs/', 'managed by configuration lifecycle'),
    ('ops/', 'managed by operator templates'),
    ('docs/', 'managed by documentation map'),
    ('reports/runtime/', 'generated by operator report commands'),
    ('reports/refactor/', 'generated/curated for handoff review'),
    ('scripts/', 'managed by Makefile command UX'),
    ('src/', 'managed by package source layout'),
    ('tests/', 'managed by test strategy'),
]

DOC_ENTRYPOINTS = {
    'README.md',
    'docs/README.md',
    'docs/operations/day0_quickstart.md',
    'docs/operations/operator_workflows.md',
    'docs/operations/configuration_lifecycle.md',
    'docs/operations/storage_paths.md',
    'docs/operations/project_management_workflow.md',
    'docs/release/release_checklist.md',
    'reports/refactor/current_refactor_state.md',
}

@dataclass(frozen=True)
class FileInventoryRow:
    path: str
    area: str
    category: str
    owner: str
    management: str
    size_bytes: int
    line_count: int
    role: str
    review_note: str


def find_project_root(start: Path | None = None) -> Path:
    start = (start or Path.cwd()).resolve()
    for candidate in [start, *start.parents]:
        if all((candidate / marker).exists() for marker in ROOT_MARKERS):
            return candidate
    raise RuntimeError(f'could not locate project root from {start}')


def _is_excluded(path: Path, root: Path) -> bool:
    rel = path.relative_to(root)
    if rel.parts and rel.parts[0] in TOP_LEVEL_EXCLUDED_PARTS:
        return True
    if any(part in EXCLUDED_PARTS or part.endswith('.egg-info') for part in rel.parts):
        return True
    if path.suffix in EXCLUDED_SUFFIXES:
        return True
    if rel.parts[:2] == ('reports', 'runtime') and any(path.name.startswith(prefix) for prefix in DYNAMIC_RUNTIME_PATTERNS):
        return True
    return False


def _first_match(path: str, rules: list[tuple[str, str]], default: str) -> str:
    return next((value for prefix, value in rules if path.startswith(prefix)), default)


def _line_count(path: Path) -> int:
    try:
        return len(path.read_text(encoding='utf-8').splitlines())
    except UnicodeDecodeError:
        return 0


def _role(path: str) -> str:
    if path in DOC_ENTRYPOINTS:
        return 'entrypoint'
    if path.endswith(('.md', '.rst')):
        return 'documentation'
    if path.endswith(('.yaml', '.yml', '.json', '.csv')):
        return 'structured-data'
    if path.endswith('.py'):
        return 'python-source'
    if path.endswith('.sh'):
        return 'shell-command'
    if path in {'Makefile', 'Dockerfile'}:
        return 'build-command'
    if path.startswith(('.env', '.python-version')):
        return 'environment-template'
    return 'supporting-file'


def _review_note(path: str) -> str:
    if path in DOC_ENTRYPOINTS:
        return 'primary navigation or current-state entrypoint; keep synchronized with Makefile and reports'
    if path.startswith('reports/runtime/'):
        return 'generated operator report; regenerate through make operator-reports before handoff'
    if path.startswith('reports/refactor/'):
        return 'handoff/review artifact; avoid stale phase snapshots in active package'
    if path.startswith('configs/'):
        return 'configuration source; validate through governance and projection checks after edits'
    if path.startswith('docs/'):
        return 'documentation; keep relative links valid and avoid duplicating current command flow'
    if path.startswith('scripts/'):
        return 'operator/developer command; expose through Makefile/help if user-facing'
    if path.startswith('src/ai_model_serving/domain/'):
        return 'registry/domain code; monitor size as projections grow'
    if path.startswith('src/'):
        return 'application code; preserve public API behavior and compatibility facades'
    if path.startswith('tests/'):
        return 'test coverage; keep deterministic and avoid live GPU dependency'
    return 'supporting project file'


def iter_inventory(root: Path) -> list[FileInventoryRow]:
    rows: list[FileInventoryRow] = []
    for path in sorted(root.rglob('*')):
        if not path.is_file() or _is_excluded(path, root):
            continue
        rel = path.relative_to(root).as_posix()
        area = rel.split('/', 1)[0]
        rows.append(FileInventoryRow(
            path=rel,
            area=area,
            category=_first_match(rel, CATEGORY_RULES, 'project metadata'),
            owner=_first_match(rel, OWNER_RULES, 'project-maintenance'),
            management=_first_match(rel, MANAGEMENT_RULES, 'managed by root project metadata'),
            size_bytes=path.stat().st_size,
            line_count=_line_count(path),
            role=_role(rel),
            review_note=_review_note(rel),
        ))
    return rows


def inventory_summary(rows: Iterable[FileInventoryRow]) -> dict[str, object]:
    row_list = list(rows)
    def counts(field: str) -> dict[str, int]:
        out: dict[str, int] = {}
        for row in row_list:
            key = getattr(row, field)
            out[key] = out.get(key, 0) + 1
        return dict(sorted(out.items()))
    large_files = [asdict(row) for row in sorted(row_list, key=lambda r: r.line_count, reverse=True)[:15]]
    return {
        'total_files': len(row_list),
        'by_area': counts('area'),
        'by_category': counts('category'),
        'by_owner': counts('owner'),
        'by_role': counts('role'),
        'large_files_by_line_count': large_files,
        'entrypoints': sorted(DOC_ENTRYPOINTS),
    }


def write_inventory_reports(root: Path, output_dir: Path | None = None) -> dict[str, Path]:
    output_dir = output_dir or root / 'reports' / 'refactor'
    output_dir.mkdir(parents=True, exist_ok=True)
    rows = iter_inventory(root)
    summary = inventory_summary(rows)
    csv_path = output_dir / 'project_inventory_current.csv'
    json_path = output_dir / 'project_inventory_current.json'
    md_path = output_dir / 'project_inventory_current.md'

    with csv_path.open('w', encoding='utf-8', newline='') as fh:
        writer = csv.DictWriter(
            fh,
            fieldnames=list(FileInventoryRow.__dataclass_fields__),
            lineterminator='\n',
        )
        writer.writeheader()
        for row in rows:
            writer.writerow(asdict(row))

    json_path.write_text(json.dumps({'summary': summary, 'files': [asdict(row) for row in rows]}, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

    lines = [
        '<!-- GENERATED FILE. DO NOT EDIT.',
        'Source:',
        '- src/ configs/ docs/ scripts/ (source tree)',
        'Command:',
        '- make project-inventory',
        '- make release-check',
        '-->',
        '',
        '# 프로젝트 인벤토리와 파일 검토 — Current',
        '',
        '이 리포트는 현재 source tree에서 생성되며 로컬 runtime/cache/build 디렉터리는 제외한다.',
        '',
        f'- 검토 파일 수: **{summary["total_files"]}**',
        f'- CSV matrix: `{csv_path.relative_to(root).as_posix()}`',
        f'- JSON matrix: `{json_path.relative_to(root).as_posix()}`',
        '',
        '## 영역별 파일 수',
        '',
        '| 영역 | 수 |',
        '|---|---:|',
    ]
    for area, count in summary['by_area'].items():
        lines.append(f'| `{area}` | {count} |')
    lines += ['', '## 주요 진입점', '']
    for entry in summary['entrypoints']:
        lines.append(f'- `{entry}`')
    lines += ['', '## 줄 수 기준 큰 파일', '', '| 경로 | 줄 수 | 담당 | 검토 메모 |', '|---|---:|---|---|']
    for row in summary['large_files_by_line_count']:
        lines.append(f'| `{row["path"]}` | {row["line_count"]} | {row["owner"]} | {row["review_note"]} |')
    lines += ['', '## 관리 해석', '', '- 사용자-facing 명령은 `Makefile`, `make help`, `docs/operations/operator_workflows.md`에 노출되어야 한다.', '- 설정 원천 파일은 `docs/operations/configuration_lifecycle.md`에 반영하고 governance validation으로 보호해야 한다.', '- 생성 runtime report는 `make operator-reports`로 갱신하고, timestamp가 붙은 live runtime validation evidence는 릴리스 패키지에 포함하지 않는다.', '', '이 inventory는 파일 목록 자체보다 관리 경계 확인이 목적이다. `src/`는 application/control-plane code, `configs/`는 설정 source of truth, `docs/`는 운영자가 읽는 문서, `reports/runtime/`은 재생성 가능한 운영 evidence, `reports/refactor/`는 current handoff를 담는다. 새 파일을 추가할 때는 이 경계에 맞는 위치인지 먼저 확인한다.', '', '오래된 phase snapshot이나 날짜가 붙은 current-state 파일은 active handoff에 다시 넣지 않는다. 현재 상태는 stable path인 `reports/refactor/current_refactor_state.md`, `reports/refactor/current_handoff_summary.md`, `reports/refactor/project_inventory_current.md`만 기준으로 본다.', '', '유지보수 관점에서는 큰 파일이 늘어날 때 책임 경계를 먼저 본다. 운영자가 직접 실행하는 스크립트는 Makefile에 노출되어야 하고, 설정 파일은 문서와 release gate가 함께 따라와야 한다. 문서만 추가하고 검증을 추가하지 않거나, 스크립트만 추가하고 운영 문서에 쓰지 않으면 UX drift로 본다.', '', '이 파일은 새 담당자가 프로젝트를 받았을 때 어디부터 봐야 하는지 알려주는 관리 지도다. 코드 검토는 큰 파일만 보는 것이 아니라, 사용자가 실제로 실행하는 흐름과 문서가 같은 순서를 말하는지 확인하는 방식으로 진행한다.', '']
    md_path.write_text('\n'.join(lines), encoding='utf-8')
    return {'csv': csv_path, 'json': json_path, 'markdown': md_path}
