from __future__ import annotations

from pathlib import Path

from .endpoint_spec import GATEWAY_ENDPOINTS, RISK_ADAPTER_ENDPOINTS, EndpointSpec
from ..openapi_contracts import find_project_root

BEGIN_MARKER = "<!-- BEGIN GENERATED ENDPOINT MATRIX -->"
END_MARKER = "<!-- END GENERATED ENDPOINT MATRIX -->"


def _schema_cell(name: str | None, schema_dir: Path) -> str:
    if name is None:
        return "—"
    exists = (schema_dir / name).exists()
    mark = "✓" if exists else "✗ missing"
    return f"`{name}` {mark}"


def _lifecycle_cell(lifecycle: str) -> str:
    return {"stable": "stable", "retired": "retired ⚠", "removed": "removed ✕"}.get(lifecycle, lifecycle)


def _render_table(endpoints: list[EndpointSpec], schema_dir: Path) -> str:
    header = "| Method | Path | Lifecycle | Auth | Request Schema | Response Schema | Operation ID |"
    sep = "|---|---|---|---|---|---|---|"
    rows = [
        f"| `{s.method}` | `{s.path}` | {_lifecycle_cell(s.lifecycle)} | `{s.auth}` "
        f"| {_schema_cell(s.request_schema, schema_dir)} "
        f"| {_schema_cell(s.response_schema, schema_dir)} "
        f"| `{s.operation_id}` |"
        for s in endpoints
    ]
    return "\n".join([header, sep] + rows)


def generate_block(schema_dir: Path | None = None) -> str:
    if schema_dir is None:
        schema_dir = find_project_root() / "specs" / "schemas"

    gw_table = _render_table(GATEWAY_ENDPOINTS, schema_dir)
    ra_table = _render_table(RISK_ADAPTER_ENDPOINTS, schema_dir)

    lines = [
        BEGIN_MARKER,
        "<!-- AUTO-GENERATED by scripts/generate_endpoint_matrix.py — do not edit manually -->",
        "",
        "#### Gateway (port 9400)",
        "",
        gw_table,
        "",
        "#### Risk Adapter (port 9405, compose 내부 전용)",
        "",
        ra_table,
        "",
        END_MARKER,
    ]
    return "\n".join(lines)


def update_doc(doc_path: Path, schema_dir: Path | None = None) -> bool:
    """Return True if the file was changed."""
    content = doc_path.read_text(encoding="utf-8")
    begin_idx = content.find(BEGIN_MARKER)
    end_idx = content.find(END_MARKER)
    if begin_idx == -1 or end_idx == -1:
        raise ValueError(
            f"Markers not found in {doc_path}. "
            f"Add {BEGIN_MARKER!r} and {END_MARKER!r} to the document first."
        )
    block = generate_block(schema_dir)
    updated = content[:begin_idx] + block + content[end_idx + len(END_MARKER):]
    if updated == content:
        return False
    doc_path.write_text(updated, encoding="utf-8")
    return True
